file_format: "1"
id: arctic
name: arctic
type: shield
url: https://github.com/kata0510/Lily58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - arctic_left
  - arctic_right